default:
  image: openjdk:8-jdk

stages:
  - build

before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script:
    - chmod +x ./gradlew
    - ./gradlew build
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - 1.16.5

after_script:
  - echo "Fin de la build"