# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "1.16.5" ]
  pull_request:
    branches: [ "1.16.5" ]

permissions:
  contents: read

jobs:
  generar-jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Hacer gradlew ejecutable
        run: chmod +x ./gradlew
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
